// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: User.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type TEmptyReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TEmptyReq) Reset()         { *m = TEmptyReq{} }
func (m *TEmptyReq) String() string { return proto.CompactTextString(m) }
func (*TEmptyReq) ProtoMessage()    {}
func (*TEmptyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{0}
}
func (m *TEmptyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TEmptyReq.Unmarshal(m, b)
}
func (m *TEmptyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TEmptyReq.Marshal(b, m, deterministic)
}
func (m *TEmptyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TEmptyReq.Merge(m, src)
}
func (m *TEmptyReq) XXX_Size() int {
	return xxx_messageInfo_TEmptyReq.Size(m)
}
func (m *TEmptyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TEmptyReq.DiscardUnknown(m)
}

var xxx_messageInfo_TEmptyReq proto.InternalMessageInfo

type TUserLoginResponse struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TUserLoginResponse) Reset()         { *m = TUserLoginResponse{} }
func (m *TUserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*TUserLoginResponse) ProtoMessage()    {}
func (*TUserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{1}
}
func (m *TUserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TUserLoginResponse.Unmarshal(m, b)
}
func (m *TUserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TUserLoginResponse.Marshal(b, m, deterministic)
}
func (m *TUserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TUserLoginResponse.Merge(m, src)
}
func (m *TUserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_TUserLoginResponse.Size(m)
}
func (m *TUserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TUserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TUserLoginResponse proto.InternalMessageInfo

func (m *TUserLoginResponse) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*TEmptyReq)(nil), "pb.TEmptyReq")
	proto.RegisterType((*TUserLoginResponse)(nil), "pb.TUserLoginResponse")
}

func init() { proto.RegisterFile("User.proto", fileDescriptor_979821478719c248) }

var fileDescriptor_979821478719c248 = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xe2, 0xe6, 0xe2, 0x0c, 0x71,
	0xcd, 0x2d, 0x28, 0xa9, 0x0c, 0x4a, 0x2d, 0x54, 0xd2, 0xe0, 0x12, 0x0a, 0x01, 0xc9, 0xfb, 0xe4,
	0xa7, 0x67, 0xe6, 0x05, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x09, 0x71, 0xb1, 0xf8,
	0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa0, 0x53, 0x41, 0xab, 0x47, 0x00, 0x00, 0x00,
}
