// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: Net.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type TRequest struct {
	Method               *string  `protobuf:"bytes,1,req,name=Method" json:"Method,omitempty"`
	Args                 []byte   `protobuf:"bytes,2,req,name=Args" json:"Args,omitempty"`
	CallbackHandler      *uint32  `protobuf:"varint,3,opt,name=CallbackHandler" json:"CallbackHandler,omitempty"`
	Token                *string  `protobuf:"bytes,4,opt,name=Token" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TRequest) Reset()         { *m = TRequest{} }
func (m *TRequest) String() string { return proto.CompactTextString(m) }
func (*TRequest) ProtoMessage()    {}
func (*TRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89df50c6e678b6ca, []int{0}
}
func (m *TRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TRequest.Unmarshal(m, b)
}
func (m *TRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TRequest.Marshal(b, m, deterministic)
}
func (m *TRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TRequest.Merge(m, src)
}
func (m *TRequest) XXX_Size() int {
	return xxx_messageInfo_TRequest.Size(m)
}
func (m *TRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TRequest proto.InternalMessageInfo

func (m *TRequest) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *TRequest) GetArgs() []byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *TRequest) GetCallbackHandler() uint32 {
	if m != nil && m.CallbackHandler != nil {
		return *m.CallbackHandler
	}
	return 0
}

func (m *TRequest) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type TResponse struct {
	Err                  *int32   `protobuf:"varint,1,req,name=Err" json:"Err,omitempty"`
	ErrMsg               *string  `protobuf:"bytes,2,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
	Method               *string  `protobuf:"bytes,3,req,name=Method" json:"Method,omitempty"`
	Ret                  []byte   `protobuf:"bytes,4,opt,name=Ret" json:"Ret,omitempty"`
	CallbackHandler      *uint32  `protobuf:"varint,5,opt,name=CallbackHandler" json:"CallbackHandler,omitempty"`
	Time                 *uint32  `protobuf:"varint,6,opt,name=Time" json:"Time,omitempty"`
	Token                *string  `protobuf:"bytes,7,opt,name=Token" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TResponse) Reset()         { *m = TResponse{} }
func (m *TResponse) String() string { return proto.CompactTextString(m) }
func (*TResponse) ProtoMessage()    {}
func (*TResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89df50c6e678b6ca, []int{1}
}
func (m *TResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TResponse.Unmarshal(m, b)
}
func (m *TResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TResponse.Marshal(b, m, deterministic)
}
func (m *TResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TResponse.Merge(m, src)
}
func (m *TResponse) XXX_Size() int {
	return xxx_messageInfo_TResponse.Size(m)
}
func (m *TResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TResponse proto.InternalMessageInfo

func (m *TResponse) GetErr() int32 {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return 0
}

func (m *TResponse) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func (m *TResponse) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *TResponse) GetRet() []byte {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *TResponse) GetCallbackHandler() uint32 {
	if m != nil && m.CallbackHandler != nil {
		return *m.CallbackHandler
	}
	return 0
}

func (m *TResponse) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *TResponse) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*TRequest)(nil), "pb.TRequest")
	proto.RegisterType((*TResponse)(nil), "pb.TResponse")
}

func init() { proto.RegisterFile("Net.proto", fileDescriptor_89df50c6e678b6ca) }

var fileDescriptor_89df50c6e678b6ca = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xce, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x06, 0x60, 0x92, 0xb4, 0xab, 0x19, 0x56, 0x5c, 0x06, 0x91, 0x1c, 0xc3, 0x9e, 0x72, 0xf2,
	0x1d, 0x44, 0x16, 0xbc, 0xac, 0x87, 0x21, 0x2f, 0xd0, 0x75, 0x87, 0x2a, 0xad, 0x4d, 0x4d, 0xa2,
	0x2f, 0xe6, 0x0b, 0x4a, 0x63, 0xc1, 0x2a, 0xbd, 0xfd, 0x7f, 0xc2, 0xf0, 0x7f, 0xa0, 0x9f, 0x38,
	0xdf, 0x8d, 0x31, 0xe4, 0x80, 0x72, 0x3c, 0xed, 0x3f, 0xe1, 0xd2, 0x13, 0xbf, 0x7f, 0x70, 0xca,
	0x78, 0x0b, 0x9b, 0x23, 0xe7, 0x97, 0x70, 0x36, 0xc2, 0x4a, 0xa7, 0x69, 0x6e, 0x88, 0x50, 0xdd,
	0xc7, 0x36, 0x19, 0x69, 0xa5, 0xdb, 0x52, 0xc9, 0xe8, 0xe0, 0xfa, 0xa1, 0xe9, 0xfb, 0x53, 0xf3,
	0xdc, 0x3d, 0x36, 0xc3, 0xb9, 0xe7, 0x68, 0x94, 0x15, 0xee, 0x8a, 0xfe, 0x3f, 0xe3, 0x0d, 0xd4,
	0x3e, 0x74, 0x3c, 0x98, 0xca, 0x0a, 0xa7, 0xe9, 0xa7, 0xec, 0xbf, 0x04, 0x68, 0x4f, 0x9c, 0xc6,
	0x30, 0x24, 0xc6, 0x1d, 0xa8, 0x43, 0x8c, 0x65, 0xb6, 0xa6, 0x29, 0x4e, 0x96, 0x43, 0x8c, 0xc7,
	0xd4, 0x1a, 0x59, 0xce, 0xe6, 0xb6, 0x30, 0xaa, 0x3f, 0xc6, 0x1d, 0x28, 0xe2, 0x5c, 0x36, 0xb6,
	0x34, 0xc5, 0x35, 0x61, 0xbd, 0x2e, 0x44, 0xa8, 0xfc, 0xeb, 0x1b, 0x9b, 0x4d, 0xf9, 0x2e, 0xf9,
	0x57, 0x7d, 0xb1, 0x50, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x72, 0x0a, 0x83, 0x3d, 0x01,
	0x00, 0x00,
}
